---
- name: Setup DB Server
  hosts: all
  become: yes
  tasks:
   - name: Print OS name
     debug: 
       var: ansible_distribution
   - name: Print Memory
     debug:
       var: ansible_memory_mb.real.free      
