---
- name: Setup WebServer
  hosts: webservers
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Start apache2
      service:
         name: apache2
         state: started 
         enabled: yes
    - name: Deploy webconfig
      copy:
        src: index.html
        dest: /var/www/html/index.html
         

- name: Setup DB Server
  hosts: dbservers
  become: yes
  tasks: 
    - name: Install MongoDB
      yum:
        name: mariadb-server
        state: present
      become: true

    - name: Start and Enable MariaDB Server
      service: 
        name: mariadb
        state: started
        enabled: yes

    - name: Install Python3-pymysql
      yum:
        name: python39-PyMySQL
        state: present

    - name: Create a new database "DevopsDB"
      mysql_db: 
        name: devopsdb
        state: present
   
    - name: Create Database user "Devops"
      mysql_user:
        name: Devops
        password: devops@123
        priv: '*.*:ALL'
        state: present        
